# Generated by Django 5.1.7 on 2025-04-16 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Amenidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('clave', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('valor', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPaquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=255)),
                ('tipo', models.PositiveSmallIntegerField(choices=[(0, 'Cliente'), (1, 'Administrador')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ImagenActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_imagen', models.TextField()),
                ('descripcion', models.TextField()),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('duracion_dias', models.IntegerField()),
                ('precio_adulto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_nino', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimo_personas', models.IntegerField()),
                ('maximo_personas', models.IntegerField()),
                ('imagen_portada_url', models.TextField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hotel')),
                ('tipo_paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipopaquete')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paquete')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_imagen', models.TextField()),
                ('descripcion', models.TextField()),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ubicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('cantidad_adultos', models.IntegerField()),
                ('cantidad_ninos', models.IntegerField()),
                ('total_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.PositiveSmallIntegerField(choices=[(0, 'Pendiente'), (1, 'Confirmada'), (2, 'Cancelada')], default=0)),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paquete')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='PaqueteActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.actividad')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paquete')),
            ],
            options={
                'unique_together': {('paquete', 'actividad')},
            },
        ),
        migrations.CreateModel(
            name='PaqueteAmenidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.amenidad')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paquete')),
            ],
            options={
                'unique_together': {('paquete', 'amenidad')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permiso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.permiso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'unique_together': {('usuario', 'permiso')},
            },
        ),
    ]
