# Generated by Django 5.1.7 on 2025-04-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.SmallIntegerField(choices=[(1, 'Administrador'), (2, 'Supervisor'), (3, 'Empleado')]),
        ),
    ]
