# Generated by Django 5.1.7 on 2025-05-03 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='url_portada',
            field=models.ImageField(blank=True, null=True, upload_to='admin/actividades/'),
        ),
        migrations.AlterField(
            model_name='imagenpaquete',
            name='url_imagen',
            field=models.ImageField(blank=True, null=True, upload_to='admin/paquetes/'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='url_portada',
            field=models.ImageField(blank=True, null=True, upload_to='admin/ubicacion/'),
        ),
    ]
