# Generated by Django 5.1.7 on 2025-05-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_actividad_url_portada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='url_portada',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='imagenpaquete',
            name='url_imagen',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='url_portada',
            field=models.TextField(),
        ),
    ]
