# Generated by Django 5.1.7 on 2025-05-13 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_paquete_hotel'),
        ('core', '0003_alter_actividad_url_portada_and_more'),
    ]

    operations = [
    ]
