# Generated by Django 5.1.7 on 2025-05-13 06:00

import apps.core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20250512_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerario',
            name='titulo',
            field=models.CharField(default='Día sin título', max_length=100),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='nombre',
            field=models.CharField(max_length=100, validators=[apps.core.models.validar_nombre_sin_numeros_y_mayuscula]),
        ),
        migrations.AlterField(
            model_name='amenidad',
            name='nombre',
            field=models.CharField(max_length=100, validators=[apps.core.models.validar_nombre_sin_numeros_y_mayuscula]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=100, validators=[apps.core.models.validar_nombre_sin_numeros_y_mayuscula]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(error_messages={'invalid': 'Por favor, ingresa un correo electrónico válido.'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=100, validators=[apps.core.models.validar_nombre_sin_numeros_y_mayuscula]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=20, validators=[apps.core.models.validar_telefono]),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='nombre',
            field=models.CharField(max_length=100, validators=[apps.core.models.validar_nombre_sin_numeros_y_mayuscula]),
        ),
        migrations.AlterField(
            model_name='itinerario',
            name='dia',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='duracion_dias',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='maximo_personas',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='minimo_personas',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='nombre',
            field=models.CharField(max_length=100, validators=[apps.core.models.validar_nombre_sin_numeros_y_mayuscula]),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='precio_adulto',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='precio_nino',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='paqueteamenidad',
            name='estado',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='cantidad_adultos',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='cantidad_ninos',
            field=models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reservacion',
            name='total_pago',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='tipopaquete',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, validators=[apps.core.models.validar_nombre_sin_numeros_y_mayuscula]),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='nombre',
            field=models.CharField(max_length=100, validators=[apps.core.models.validar_nombre_sin_numeros_y_mayuscula]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(max_length=255, validators=[apps.core.models.validar_contrasena]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(error_messages={'invalid': 'Por favor, ingresa un correo electrónico válido.'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(max_length=100, validators=[apps.core.models.validar_usuario]),
        ),
    ]
