# Generated by Django 5.1.7 on 2025-05-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20250506_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerario',
            name='titulo',
            field=models.CharField(default='Dia sin título', max_length=100),
        ),
    ]
